if(EXISTS "/home/wuledan/work/proj/storage-engine/build_sanitized/tests/stress/test_io_stress[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_sanitized/tests/stress/test_io_stress[1]_tests.cmake")
else()
  add_test(test_io_stress_NOT_BUILT test_io_stress_NOT_BUILT)
endif()
