if(EXISTS "/home/wuledan/work/proj/storage-engine/build_debug/tests/stress/test_stress[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_debug/tests/stress/test_stress[1]_tests.cmake")
else()
  add_test(test_stress_NOT_BUILT test_stress_NOT_BUILT)
endif()
