if(EXISTS "/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_perf_comprehensive[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_perf_comprehensive[1]_tests.cmake")
else()
  add_test(test_perf_comprehensive_NOT_BUILT test_perf_comprehensive_NOT_BUILT)
endif()
