if(EXISTS "/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_work_queues[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_work_queues[1]_tests.cmake")
else()
  add_test(test_work_queues_NOT_BUILT test_work_queues_NOT_BUILT)
endif()
