if(EXISTS "/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_types[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_types[1]_tests.cmake")
else()
  add_test(test_types_NOT_BUILT test_types_NOT_BUILT)
endif()
