add_test([=[WorkerTest.Lifecycle]=]  /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_worker [==[--gtest_filter=WorkerTest.Lifecycle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WorkerTest.Lifecycle]=]  PROPERTIES WORKING_DIRECTORY /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WorkerTest.AddQueueBeforeStart]=]  /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_worker [==[--gtest_filter=WorkerTest.AddQueueBeforeStart]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WorkerTest.AddQueueBeforeStart]=]  PROPERTIES WORKING_DIRECTORY /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WorkerTest.NotifyWakesIdle]=]  /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_worker [==[--gtest_filter=WorkerTest.NotifyWakesIdle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WorkerTest.NotifyWakesIdle]=]  PROPERTIES WORKING_DIRECTORY /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WorkerTest.StatsAccumulate]=]  /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_worker [==[--gtest_filter=WorkerTest.StatsAccumulate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WorkerTest.StatsAccumulate]=]  PROPERTIES WORKING_DIRECTORY /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WorkerTest.IndependentWorkers]=]  /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_worker [==[--gtest_filter=WorkerTest.IndependentWorkers]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WorkerTest.IndependentWorkers]=]  PROPERTIES WORKING_DIRECTORY /home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_worker_TESTS WorkerTest.Lifecycle WorkerTest.AddQueueBeforeStart WorkerTest.NotifyWakesIdle WorkerTest.StatsAccumulate WorkerTest.IndependentWorkers)
