if(EXISTS "/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_decision_system[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_decision_system[1]_tests.cmake")
else()
  add_test(test_decision_system_NOT_BUILT test_decision_system_NOT_BUILT)
endif()
