if(EXISTS "/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_coroutine_worker[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_coroutine_worker[1]_tests.cmake")
else()
  add_test(test_coroutine_worker_NOT_BUILT test_coroutine_worker_NOT_BUILT)
endif()
