if(EXISTS "/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_executor[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_sanitized/tests/unit/test_executor[1]_tests.cmake")
else()
  add_test(test_executor_NOT_BUILT test_executor_NOT_BUILT)
endif()
