if(EXISTS "/home/wuledan/work/proj/storage-engine/build_debug/tests/module/test_io_integration[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_debug/tests/module/test_io_integration[1]_tests.cmake")
else()
  add_test(test_io_integration_NOT_BUILT test_io_integration_NOT_BUILT)
endif()
