if(EXISTS "/home/wuledan/work/proj/storage-engine/build_debug/tests/module/test_concurrent[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_debug/tests/module/test_concurrent[1]_tests.cmake")
else()
  add_test(test_concurrent_NOT_BUILT test_concurrent_NOT_BUILT)
endif()
