if(EXISTS "/home/wuledan/work/proj/storage-engine/build_debug/tests/unit/test_batch_submit[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_debug/tests/unit/test_batch_submit[1]_tests.cmake")
else()
  add_test(test_batch_submit_NOT_BUILT test_batch_submit_NOT_BUILT)
endif()
