if(EXISTS "/home/wuledan/work/proj/storage-engine/build_debug/tests/unit/test_error_codes[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_debug/tests/unit/test_error_codes[1]_tests.cmake")
else()
  add_test(test_error_codes_NOT_BUILT test_error_codes_NOT_BUILT)
endif()
