if(EXISTS "/home/wuledan/work/proj/storage-engine/build_debug/tests/unit/test_runtime[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_debug/tests/unit/test_runtime[1]_tests.cmake")
else()
  add_test(test_runtime_NOT_BUILT test_runtime_NOT_BUILT)
endif()
