if(EXISTS "/home/wuledan/work/proj/storage-engine/build_debug/tests/unit/test_worker[1]_tests.cmake")
  include("/home/wuledan/work/proj/storage-engine/build_debug/tests/unit/test_worker[1]_tests.cmake")
else()
  add_test(test_worker_NOT_BUILT test_worker_NOT_BUILT)
endif()
